name: tekartik_cmd_utils
description: Linux command line tools
version: 0.3.0
homepage: https://github.com/tekartik/cmd_utils.dart
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  args: any
  csv: any
  glob: any
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: dart2
    version: '>=0.5.1'
  process_run: '>=0.5.4'

dev_dependencies:
  test: ">=1.0.0"
  dev_test: any
  process_run: '>=0.10.2'
