name: tekartik_cmd_utils
description: Linux command line tools
version: 0.4.0
homepage: https://github.com/tekartik/cmd_utils.dart

publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: any
  csv: any
  glob: any
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart2_3
    version: '>=0.5.1'
  process_run: '>=0.10.2'

dev_dependencies:
  test: ">=1.0.0"
  dev_test: '>=0.13.2-dev.3'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
